[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
evm_version = "osaka"
cbor_metadata = true
bytecode_hash = "none"
use_literal_content = true
eth-rpc-url = "monad_testnet"
chain_id = 10143

[rpc_endpoints]
monad_testnet = "${MONAD_TESTNET_RPC_URL}"

[fmt]
line_length = 100

[invariant]
runs = 32
depth = 32
fail_on_revert = false

[lint]
exclude_lints = ["multi-contract-file"]
