// Generated from deployments/monad-testnet.json by scripts/sync-deployment.mjs.
// Do not edit this file or add the development-only health-check receipt to the product API.

import type { Address, Hash } from "viem";

export interface SubmissionReceiptRegistryDeployment {
  readonly manifestSchemaVersion: string;
  readonly network: { readonly name: string; readonly chainId: number };
  readonly contract: {
    readonly name: string;
    readonly address: Address;
    readonly protocolVersion: number;
    readonly fullyQualifiedSource: string;
  };
  readonly compilation: {
    readonly solidityVersion: string;
    readonly optimizer: { readonly enabled: boolean; readonly runs: number };
    readonly evmVersion: string;
    readonly metadata: {
      readonly cbor: boolean;
      readonly bytecodeHash: string;
      readonly useLiteralContent: boolean;
    };
    readonly abiSha256: string;
  };
  readonly deployment: {
    readonly transactionHash: Hash;
    readonly blockNumber: string;
    readonly deployer: Address;
    readonly deployedAt: string;
    readonly sourceCommit: string;
  };
  readonly runtimeBytecode: { readonly sizeBytes: number; readonly keccak256: Hash };
  readonly sourceVerification: {
    readonly provider: string;
    readonly jobId: string;
    readonly jobUrl: string;
    readonly completed: boolean;
    readonly status: "match";
    readonly runtimeMatch: "match";
    readonly creationMatch: null;
    readonly verifiedAt: string;
  };
  readonly explorers: {
    readonly monadVision: DeploymentExplorerLinks;
    readonly monadscan: DeploymentExplorerLinks;
  };
}

export interface DeploymentExplorerLinks {
  readonly baseUrl: string;
  readonly contractUrl: string;
  readonly deploymentTransactionUrl: string;
  readonly deploymentBlockUrl: string;
}

export const SUBMITTEDIT_MONAD_TESTNET_CHAIN_ID = 10143 as const;
export const SUBMISSION_RECEIPT_REGISTRY_ADDRESS =
  "0x63914900a2D3571F92506821a76c4036C3e25883" as const satisfies Address;

export const submissionReceiptRegistryDeployment = {
  manifestSchemaVersion: "1.0",
  network: {
    name: "Monad Testnet",
    chainId: 10143,
  },
  contract: {
    name: "SubmissionReceiptRegistry",
    address: "0x63914900a2D3571F92506821a76c4036C3e25883",
    protocolVersion: 1,
    fullyQualifiedSource: "src/SubmissionReceiptRegistry.sol:SubmissionReceiptRegistry",
  },
  compilation: {
    solidityVersion: "0.8.30+commit.73712a01",
    optimizer: {
      enabled: true,
      runs: 200,
    },
    evmVersion: "osaka",
    metadata: {
      cbor: true,
      bytecodeHash: "none",
      useLiteralContent: true,
    },
    abiSha256: "e3620a954c3e3426a244cac025af41afd2bbfb116eecafb7dad6e186cdb50165",
  },
  deployment: {
    transactionHash: "0xc366e3ca93cd5ae49ac0dd90d95621fa0dee76fefb5deb4ecbc47122a01ab38e",
    blockNumber: "45213264",
    deployer: "0xD509Af69953aAB34dB20e46F0d104348639976fD",
    deployedAt: "2026-07-15T19:57:39Z",
    sourceCommit: "d5250f0e3621e483bf27a0edfc538e2f02178473",
  },
  runtimeBytecode: {
    sizeBytes: 1913,
    keccak256: "0xfbd38ff7e797a7c959d4d55b2eb6dd3987640e60bb97ffbb5b838b0021aeefae",
  },
  sourceVerification: {
    provider: "MonadVision / Sourcify",
    jobId: "e136f18f-a9ba-4dac-879c-be0193376ec6",
    jobUrl:
      "https://sourcify-api-monad.blockvision.org/v2/verify/e136f18f-a9ba-4dac-879c-be0193376ec6",
    completed: true,
    status: "match",
    runtimeMatch: "match",
    creationMatch: null,
    verifiedAt: "2026-07-15T23:11:20Z",
  },
  explorers: {
    monadVision: {
      baseUrl: "https://testnet.monadvision.com",
      contractUrl:
        "https://testnet.monadvision.com/address/0x63914900a2D3571F92506821a76c4036C3e25883",
      deploymentTransactionUrl:
        "https://testnet.monadvision.com/tx/0xc366e3ca93cd5ae49ac0dd90d95621fa0dee76fefb5deb4ecbc47122a01ab38e",
      deploymentBlockUrl: "https://testnet.monadvision.com/block/45213264",
    },
    monadscan: {
      baseUrl: "https://testnet.monadscan.com",
      contractUrl:
        "https://testnet.monadscan.com/address/0x63914900a2D3571F92506821a76c4036C3e25883",
      deploymentTransactionUrl:
        "https://testnet.monadscan.com/tx/0xc366e3ca93cd5ae49ac0dd90d95621fa0dee76fefb5deb4ecbc47122a01ab38e",
      deploymentBlockUrl: "https://testnet.monadscan.com/block/45213264",
    },
  },
} as const satisfies SubmissionReceiptRegistryDeployment;
